### PR TITLE
Adds the travis build icon to the README

### PR DESCRIPTION
**Pull request by lobabob**

### CODE REVIEW

**Comment by lobabob** [comment]
blah

**Comment by lobabob** [comment]
asdf

**Comment by keitharm** [comment]
##############

**Comment by keitharm** [comment]
#22

**Comment by lobabob** [comment]
#27

**Comment by lobabob** [comment]
#18

**Comment by lobabob** [comment]
#19

**Comment by lobabob** [comment]
#20

**Comment by keitharm** [comment]
#19

**Comment by keitharm** [comment]
#20

**Comment by keitharm** [comment]
#20

**Comment by keitharm** [comment]
asdf #20 asdf

**Pull request closed without merging**
